Creating filelist for public/angularjs
Creating filelist for public/angularjs/controllers
Creating filelist for public/js
Creating filelist for test/angularjs/controllers
Creating filelist for test/angularjs
Creating filelist for test
Creating filelist for test/min
Creating filelist for test/spec
Creating filelist for views
Creating filelist for views/partials
Categorizing files.
Computing results.


41	js	public/angularjs	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/public/angularjs/app.js
5	jscm	public/angularjs	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/public/angularjs/app.js.cm
68	js	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/public/angularjs/controllers/controller.js
14	jscm	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/public/angularjs/controllers/controller.js.cm
38	js	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/public/angularjs/controllers/indexCtrl.js
2	jscm	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/public/angularjs/controllers/indexCtrl.js.cm
46	js	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/public/angularjs/controllers/loginCtrl.js
16	jscm	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/public/angularjs/controllers/loginCtrl.js.cm
4	js	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/public/angularjs/controllers/writeCtrl.js
1	jscm	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/public/angularjs/controllers/writeCtrl.js.cm
397	js	public/js	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/public/js/roundProgress.js
29	jscm	public/js	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/public/js/roundProgress.js.cm
41	js	test/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/test/angularjs/controllers/indexCtrl.js
14	jscm	test/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/test/angularjs/controllers/indexCtrl.js.cm
0	js	test/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/test/angularjs/controllers/loginControllers.js
0	jscm	test/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/test/angularjs/controllers/loginControllers.js.cm
12	js	test/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/test/angularjs/controllers/writeCtrl.js
0	jscm	test/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/test/angularjs/controllers/writeCtrl.js.cm
13	js	test/angularjs	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/test/angularjs/loginCtrlSpec.js
34	jscm	test/angularjs	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/test/angularjs/loginCtrlSpec.js.cm
53	js	test	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/test/karma.conf.js
34	jscm	test	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/test/karma.conf.js.cm
1	js	test/min	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/test/min/header-controller-min.js
0	jscm	test/min	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/test/min/header-controller-min.js.cm
1	js	test/min	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/test/min/karma.conf-min.js
0	jscm	test/min	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/test/min/karma.conf-min.js.cm
36	js	test	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/test/readScript.js
8	jscm	test	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/test/readScript.js.cm
66	js	test	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/test/saveScript.js
6	jscm	test	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/test/saveScript.js.cm
45	js	test	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/test/snsLogin.js
3	jscm	test	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/test/snsLogin.js.cm
23	js	test/spec	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/test/spec/testsTest.js
3	jscm	test/spec	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/test/spec/testsTest.js.cm
32	html	views	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/views/index.html
1	htmlcm	views	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/views/index.html.cm
14	html	views/partials	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/views/partials/login.html
0	htmlcm	views/partials	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/views/partials/login.html.cm
41	html	views/partials	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/views/partials/textlist.html
1	htmlcm	views/partials	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/views/partials/textlist.html.cm
2	html	views/partials	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/views/partials/view1.html
0	htmlcm	views/partials	/Users/jaisonoh/WebstormProjects/speech0.6/speecher/speecherServer/views/partials/view1.html.cm
