Creating filelist for public/angularjs
Creating filelist for public/angularjs/controllers
Creating filelist for public/angularjs/directives
Creating filelist for public/angularjs/services
Creating filelist for public/js
Creating filelist for test/angularjs/controllers
Creating filelist for test/angularjs/directives
Creating filelist for test/angularjs/services
Creating filelist for test
Creating filelist for test/protractorjs
Creating filelist for views
Creating filelist for views/partials
Categorizing files.
Computing results.


64	js	public/angularjs	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/public/angularjs/app.js
8	jscm	public/angularjs	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/public/angularjs/app.js.cm
4	js	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/public/angularjs/controllers/choiceCtrl.js
1	jscm	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/public/angularjs/controllers/choiceCtrl.js.cm
68	js	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/public/angularjs/controllers/controller.js
14	jscm	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/public/angularjs/controllers/controller.js.cm
38	js	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/public/angularjs/controllers/indexCtrl.js
2	jscm	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/public/angularjs/controllers/indexCtrl.js.cm
64	js	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/public/angularjs/controllers/login.controller.js
5	jscm	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/public/angularjs/controllers/login.controller.js.cm
39	js	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/public/angularjs/controllers/write.controller.js
1	jscm	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/public/angularjs/controllers/write.controller.js.cm
28	js	public/angularjs/directives	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/public/angularjs/directives/write.directive.js
0	jscm	public/angularjs/directives	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/public/angularjs/directives/write.directive.js.cm
109	js	public/angularjs/services	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/public/angularjs/services/login.service.js
6	jscm	public/angularjs/services	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/public/angularjs/services/login.service.js.cm
397	js	public/js	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/public/js/roundProgress.js
29	jscm	public/js	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/public/js/roundProgress.js.cm
40	js	test/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/angularjs/controllers/indexCtrl.js
14	jscm	test/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/angularjs/controllers/indexCtrl.js.cm
34	js	test/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/angularjs/controllers/login.controller.spec.js
17	jscm	test/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/angularjs/controllers/login.controller.spec.js.cm
39	js	test/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/angularjs/controllers/write.controller.spec.js
12	jscm	test/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/angularjs/controllers/write.controller.spec.js.cm
33	js	test/angularjs/directives	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/angularjs/directives/write.directive.spec.js
18	jscm	test/angularjs/directives	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/angularjs/directives/write.directive.spec.js.cm
42	js	test/angularjs/services	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/angularjs/services/login.service.spec.js
16	jscm	test/angularjs/services	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/angularjs/services/login.service.spec.js.cm
55	js	test	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/karma.conf.js
36	jscm	test	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/karma.conf.js.cm
4	js	test/protractorjs	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/protractorjs/conf.js
0	jscm	test/protractorjs	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/protractorjs/conf.js.cm
7	js	test/protractorjs	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/protractorjs/index-spec.js
16	jscm	test/protractorjs	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/protractorjs/index-spec.js.cm
11	js	test/protractorjs	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/protractorjs/write-spec.js
2	jscm	test/protractorjs	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/protractorjs/write-spec.js.cm
36	js	test	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/readScript.js
8	jscm	test	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/readScript.js.cm
66	js	test	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/saveScript.js
6	jscm	test	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/saveScript.js.cm
45	js	test	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/snsLogin.js
3	jscm	test	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/snsLogin.js.cm
22	js	test	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/testHistory.js
4	jscm	test	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/testHistory.js.cm
64	js	test	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/testsTest.js
4	jscm	test	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/test/testsTest.js.cm
32	html	views	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/views/index.html
1	htmlcm	views	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/views/index.html.cm
14	html	views/partials	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/views/partials/login.html
0	htmlcm	views/partials	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/views/partials/login.html.cm
41	html	views/partials	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/views/partials/textlist.html
1	htmlcm	views/partials	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/views/partials/textlist.html.cm
2	html	views/partials	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/views/partials/view1.html
0	htmlcm	views/partials	/Users/jaisonoh/WebstormProjects/speecher0.9/speecher/speecherServer/views/partials/view1.html.cm
