Creating filelist for public/angularjs
Creating filelist for public/angularjs/controllers
Creating filelist for public/angularjs/directives
Creating filelist for public/angularjs/filter
Creating filelist for public/angularjs/services
Creating filelist for public/js
Creating filelist for test/angularjs/controllers
Creating filelist for test/angularjs/directives
Creating filelist for test/angularjs/services
Creating filelist for test
Creating filelist for test/protractorjs
Creating filelist for views
Creating filelist for views/partials
Categorizing files.
Computing results.


84	js	public/angularjs	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/app.js
13	jscm	public/angularjs	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/app.js.cm
27	js	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/controllers/choice.controller.js
7	jscm	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/controllers/choice.controller.js.cm
93	js	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/controllers/detail.controller.js
5	jscm	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/controllers/detail.controller.js.cm
102	js	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/controllers/index.controller.js
11	jscm	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/controllers/index.controller.js.cm
65	js	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/controllers/login.controller.js
5	jscm	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/controllers/login.controller.js.cm
48	js	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/controllers/result.controller.js
6	jscm	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/controllers/result.controller.js.cm
202	js	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/controllers/test.controller.js
16	jscm	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/controllers/test.controller.js.cm
42	js	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/controllers/write.controller.js
3	jscm	public/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/controllers/write.controller.js.cm
28	js	public/angularjs/directives	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/directives/write.directive.js
0	jscm	public/angularjs/directives	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/directives/write.directive.js.cm
111	js	public/angularjs/filter	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/filter/diff.filter.js
5	jscm	public/angularjs/filter	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/filter/diff.filter.js.cm
107	js	public/angularjs/services	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/services/choice.service.js
8	jscm	public/angularjs/services	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/services/choice.service.js.cm
109	js	public/angularjs/services	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/services/login.service.js
6	jscm	public/angularjs/services	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/services/login.service.js.cm
52	js	public/angularjs/services	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/services/script.service.js
2	jscm	public/angularjs/services	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/services/script.service.js.cm
34	js	public/angularjs/services	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/services/test.service.js
2	jscm	public/angularjs/services	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/angularjs/services/test.service.js.cm
65	js	public/js	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/js/record.js
7	jscm	public/js	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/js/record.js.cm
397	js	public/js	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/js/roundProgress.js
29	jscm	public/js	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/js/roundProgress.js.cm
0	js	public/js	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/js/timer.js
46	jscm	public/js	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/js/timer.js.cm
16	js	public/js	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/js/tts.js
1	jscm	public/js	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/public/js/tts.js.cm
0	js	test/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/angularjs/controllers/indexCtrl.js
61	jscm	test/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/angularjs/controllers/indexCtrl.js.cm
34	js	test/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/angularjs/controllers/login.controller.spec.js
17	jscm	test/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/angularjs/controllers/login.controller.spec.js.cm
39	js	test/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/angularjs/controllers/write.controller.spec.js
16	jscm	test/angularjs/controllers	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/angularjs/controllers/write.controller.spec.js.cm
33	js	test/angularjs/directives	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/angularjs/directives/write.directive.spec.js
18	jscm	test/angularjs/directives	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/angularjs/directives/write.directive.spec.js.cm
42	js	test/angularjs/services	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/angularjs/services/login.service.spec.js
16	jscm	test/angularjs/services	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/angularjs/services/login.service.spec.js.cm
45	js	test/angularjs/services	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/angularjs/services/script.service.spec.js
11	jscm	test/angularjs/services	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/angularjs/services/script.service.spec.js.cm
20	js	test	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/deleteScript.js
7	jscm	test	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/deleteScript.js.cm
58	js	test	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/karma.conf.js
35	jscm	test	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/karma.conf.js.cm
51	js	test	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/mainTest.js
4	jscm	test	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/mainTest.js.cm
4	js	test/protractorjs	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/protractorjs/conf.js
0	jscm	test/protractorjs	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/protractorjs/conf.js.cm
7	js	test/protractorjs	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/protractorjs/index-spec.js
16	jscm	test/protractorjs	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/protractorjs/index-spec.js.cm
11	js	test/protractorjs	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/protractorjs/write-spec.js
2	jscm	test/protractorjs	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/protractorjs/write-spec.js.cm
50	js	test	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/readScript.js
9	jscm	test	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/readScript.js.cm
66	js	test	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/saveScript.js
6	jscm	test	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/saveScript.js.cm
60	js	test	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/scriptDetailTest.js
3	jscm	test	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/scriptDetailTest.js.cm
45	js	test	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/snsLogin.js
3	jscm	test	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/snsLogin.js.cm
22	js	test	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/testHistory.js
4	jscm	test	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/testHistory.js.cm
46	js	test	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/testsTest.js
5	jscm	test	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/test/testsTest.js.cm
32	html	views	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/views/index.html
1	htmlcm	views	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/views/index.html.cm
14	html	views/partials	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/views/partials/login.html
0	htmlcm	views/partials	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/views/partials/login.html.cm
41	html	views/partials	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/views/partials/textlist.html
1	htmlcm	views/partials	/Users/jaisonoh/WebstormProjects/speecher1.9/speecher/speecherServer/views/partials/textlist.html.cm
